### PR TITLE
Picsure 185 auth0 integration

### PR DESCRIPTION
**Pull request by gaborkorodi-hms**
Time to release all changes, for a new release

### CODE REVIEW

**Comment by gaborkorodi-hms** [comment]
Please remove branch `185` once merged. Please note, that once the `master` branch is updated with these changes, docker images will be built.

**Comment by namdets** [comment]
This cannot be merged because the files were moved from the /admin path to /

As we had discussed before, every single app needs to have a base path and the psamaui should use the base path /psamaui

Please fix the paths.

**Comment by gaborkorodi-hms** [comment]
Done. Path has been fixed. Check commit 6908ccc2b6f5ebd7f4effdda2a7d7836782f3952

https://github.com/hms-dbmi/pic-sure-auth-microapp/pull/32/commits/6908ccc2b6f5ebd7f4effdda2a7d7836782f3952



On Feb 22, 2019, at 1:49 PM, Jason Stedman <notifications@github.com<mailto:notifications@github.com>> wrote:


This cannot be merged because the files were moved from the /admin path to /

As we had discussed before, every single app needs to have a base path and the psamaui should use the base path /psamaui

Please fix the paths.

**Comment by gaborkorodi-hms** [comment]
Nope. Failed test. More fixes coming. Give me 10 minutes

On Feb 22, 2019, at 2:08 PM, Gabor Korodi <gabor_korodi@hms.harvard.edu<mailto:gabor_korodi@hms.harvard.edu>> wrote:

Done. Path has been fixed. Check commit 6908ccc2b6f5ebd7f4effdda2a7d7836782f3952

https://github.com/hms-dbmi/pic-sure-auth-microapp/pull/32/commits/6908ccc2b6f5ebd7f4effdda2a7d7836782f3952



On Feb 22, 2019, at 1:49 PM, Jason Stedman <notifications@github.com<mailto:notifications@github.com>> wrote:


This cannot be merged because the files were moved from the /admin path to /

As we had discussed before, every single app needs to have a base path and the psamaui should use the base path /psamaui

Please fix the paths.

**Comment by gaborkorodi-hms** [comment]
NOW it works. Tested (kind-of) locally.

See the new commit (based on jason_udn branch’s psama-ui source code)

https://github.com/hms-dbmi/pic-sure-auth-microapp/commit/cf5949953788232a6c813c3b90c4e6eaacd143ea




On Feb 22, 2019, at 1:49 PM, Jason Stedman <notifications@github.com<mailto:notifications@github.com>> wrote:


This cannot be merged because the files were moved from the /admin path to /

As we had discussed before, every single app needs to have a base path and the psamaui should use the base path /psamaui

Please fix the paths.

**Pull request merged**
